# Generated by Django 2.2.2 on 2020-03-23 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fresher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('SecondName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FresherQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=100)),
                ('Course_Type', models.CharField(max_length=100)),
                ('Passing_Year', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobkarleapp.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ImageField(upload_to='profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Company_Description', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Roles_and_Responsabulity', models.CharField(max_length=100)),
                ('Iterview_Date', models.DateField()),
                ('Interview_Location', models.CharField(max_length=100)),
                ('Min_Salary', models.CharField(blank=True, choices=[('50,000', '50000'), ('100,000', '100,000'), ('200,000', '200,000'), ('300,000', '300,000'), ('400,000', '400,000'), ('500,000', '500,000'), ('600,000', '600,000'), ('700,000', '700,000'), ('800,000', '800,000'), ('900,000', '900,000'), ('10,00,000', '10,00,000')], max_length=100)),
                ('Max_Salary', models.CharField(blank=True, choices=[('50,000', '50000'), ('100,000', '100,000'), ('200,000', '200,000'), ('300,000', '300,000'), ('400,000', '400,000'), ('500,000', '500,000'), ('600,000', '600,000'), ('700,000', '700,000'), ('800,000', '800,000'), ('900,000', '900,000'), ('10,00,000', '10,00,000')], max_length=100)),
                ('Min_Exp', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('Max_Exp', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('First_HrName', models.CharField(max_length=100)),
                ('Second_HrName', models.CharField(max_length=100)),
                ('First_HrNumber', models.IntegerField()),
                ('Second_HrNumber', models.IntegerField()),
                ('fresherqualification', models.ManyToManyField(to='jobkarleapp.FresherQualification')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['CompanyName'],
            },
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Course',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobkarleapp.Qualification_Course'),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Highest_Qualification',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobkarleapp.Qualification'),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FresherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('male', 'Male.'), ('female', 'Female.'), ('other', 'Other')], max_length=4)),
                ('Nationality', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
