# Generated by Django 2.2.2 on 2020-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresherdata',
            name='Address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fresherdata',
            name='Age',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range1',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range2',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range3',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range4',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range5',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Range6',
            field=models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='Skills6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrequirments',
            name='fresherqualification',
            field=models.ManyToManyField(blank=True, to='jobkarleapp.FresherQualification'),
        ),
    ]
