# Generated by Django 2.2.2 on 2020-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0003_auto_20200323_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresherqualification',
            name='Phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
