# Generated by Django 2.2.2 on 2020-04-07 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0004_fresherqualification_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fresherqualification',
            name='Course',
        ),
        migrations.AddField(
            model_name='fresherqualification',
            name='SubQualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fresherdata',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male.'), ('female', 'Female.'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='fresherdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
