# Generated by Django 2.2.2 on 2020-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0006_auto_20200407_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherqualification',
            name='Specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fresherqualification',
            name='SubQualification',
            field=models.CharField(blank=True, choices=[('0', '0')], max_length=100, null=True),
        ),
    ]
