# Generated by Django 2.2.2 on 2020-04-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0007_auto_20200407_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherqualification',
            name='SubQualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
