# Generated by Django 2.2.2 on 2020-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0008_auto_20200408_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherqualification',
            name='Specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fresherqualification',
            name='SubQualification',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
