# Generated by Django 2.2.2 on 2020-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0009_auto_20200408_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherqualification',
            name='Specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
