# Generated by Django 2.2.2 on 2020-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0010_auto_20200408_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimg',
            name='Profile',
            field=models.FileField(upload_to='profile'),
        ),
    ]
