# Generated by Django 2.2.2 on 2020-05-01 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0012_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirments',
            name='Company_Description',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
