# Generated by Django 2.2.2 on 2020-05-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0013_auto_20200501_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequirments',
            options={},
        ),
    ]
