# Generated by Django 2.2.2 on 2020-05-01 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0014_auto_20200501_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirments',
            name='Company_Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='Message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
