# Generated by Django 2.2.2 on 2020-05-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0015_auto_20200501_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequirments',
            options={'ordering': ['CompanyName']},
        ),
    ]
