# Generated by Django 2.2.2 on 2020-05-01 08:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0016_auto_20200501_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherqualification',
            name='Skills1',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100),
        ),
    ]
