# Generated by Django 2.2.2 on 2020-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0017_auto_20200501_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fresherqualification',
            name='Skills1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
