# Generated by Django 2.2.2 on 2020-05-03 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0018_auto_20200501_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
