# Generated by Django 2.2.2 on 2020-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0019_auto_20200503_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
