# Generated by Django 2.2.2 on 2020-05-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0021_notifications_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='Profile',
        ),
    ]
