# Generated by Django 2.2.2 on 2020-05-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0022_remove_notifications_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Profile',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
